# レビュー機能に関する設定
[pr_reviewer]
extra_instructions = "あなたは経験豊富なソフトウェアエンジニアです。日本語で、丁寧かつ建設的なレビューをしてください。"

# 要約機能に関する設定
[pr_description]
extra_instructions = """
プルリクエストの変更内容を分析し、以下の項目を日本語で記述してください。
- **概要**: 変更の目的と全体像
- **主な変更点**: ファイルごとの具体的な変更内容
- **種類**: (例: 機能追加, バグ修正, リファクタリング)
"""

# コード改善提案機能に関する設定
[pr_improver]
extra_instructions = "コードの改善案を提示してください。その際、なぜそのように変更するのか、理由も日本語で簡潔に説明してください。"

# CHANGELOG更新機能に関する設定
[pr_changelog]
extra_instructions = """
このプルリクエストの変更内容を、ユーザー向けに分かりやすく日本語で1〜2行の簡潔な箇条書きにしてください。
フォーマットは `- (種類): (変更内容の要約)` としてください。
例: `- ✨ 機能: 新しいユーザープロフィールページを追加しました。`
"""
